name: Website scrape

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru
    - cron: '0 */1 * * *'
jobs:
  # I'm running these as two seperate jobs so that in case one fails, the other will at least pass and commit the changes.
  scrape-raw:
    name: Scrape website and commit to the repository
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Install httrack
        run: sudo apt-get install httrack
      - name: Configure git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Download website
        # https://www.httrack.com/html/httrack.man.html
        run: httrack -O ./neos-raw --depth=0 --mirror https://neos.com/+*.css https://neos.com/+*.js https://neos.com/+*.gif
      - name: Commit and push
        run:  |
          git pull
          git add neos-raw/*
          git commit -m "Raw Website scrape $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
  scrape-local:
    name: Scrape local browser friendly version of the website
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Install httrack
        run: sudo apt-get install httrack
      - name: Configure git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Download local friendly website
        # This version of the command rewrites all links and downloads other resources from the website like images
        run: httrack --near -%l "en, --quiet *" https://neos.com -O1 "./neos-local" +*.css +*.js -ad.doubleclick.net/* +*.gif +*.jpg +*.jpeg +*.png +*.tif +*.bmp +*.zip +*.tar +*.tgz +*.gz +*.rar +*.z +*.mov +*.mpg +*.mpeg +*.avi +*.asf +*.mp3 +*.mp2 +*.rm +*.wav +*.vob +*.qt +*.vid +*.ac3 +*.wma +*.wmv +*.pdf
      - name: Commit and push
        run:  |
          git pull
          git add neos-local/*
          git commit -m "Local Friendly Website scrape $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main