name: Website scrape

on:
  workflow_dispatch:
  schedule:
    # At minute 0 past every 6th hour. https://crontab.guru
    - cron: '0 */6 * * *'
jobs:
  build:
    name: Scrape website and commit to the repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install httrack
        run: apt-get install httrack
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Download website
        # https://www.httrack.com/html/httrack.man.html
        run: httrack -O ./neos --depth=0 --mirror https://neos.com/
      - name: Commit website
      - run: git add *
      - run: git commit -m "Website scrape ${{ steps.date.outputs.date }}"
      - run: git push origin main