name: Website scrape

on:
  workflow_dispatch:
  schedule:
    # At minute 0 past every 6th hour. https://crontab.guru
    - cron: '0 */3 * * *'
jobs:
  build:
    name: Scrape website and commit to the repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install httrack
        run: sudo apt-get install httrack
      - name: Configure git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Download website
        # https://www.httrack.com/html/httrack.man.html
        run: httrack -O ./neos --depth=0 --mirror https://neos.com/
      - name: Commit and push
        run:  |
          git add *
          git commit -m "Website scrape $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main